### PR TITLE
Updated to current build process

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by donny-dont** [comment]
@tboerger the logrus stuff will need to be updated now.

**Comment by tboerger** [comment]
I will try to fix the remaining PRs within the next days.

**Comment by tboerger** [comment]
@donny-dont I have fixed the dependency tree.

**Comment by tboerger** [comment]
ping @drone-plugins/maintainers

**Review by appleboy — APPROVED** [review]

**Review by tonglil — APPROVED** [review]

**Comment by tonglil** [comment]
LGTM. Can't merge.

**Pull request merged**
